spring:
  config:
    activate:
      on-profile: prod

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.25:3306/sstrip_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: tripuser
    password: sangbong123123!

  # attachfile
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: Z:/home/files
